// Grid Functionality - Action Types
export const GENERATE_GRID = 'GENERATE_GRID';
export const CHANGE_GRID_SIZE = 'CHANGE_GRID_SIZE';
export const REPEAT_NUMBER_IN_GRID = 'REPEAT_NUMBER_IN_GRID';
export const SELF_ORGANIZE_DATA = 'SELF_ORGANIZE_DATA';
export const SORT_GRID = 'SORT_GRID';
export const SEARCH_ELEMENT = 'SEARCH_ELEMENT';

// Linear Search Algorithm - Action Types
export const LINEAR_SEARCH_CURRENT_VALUE = 'LINEAR_SEARCH_CURRENT_VALUE';
export const LINEAR_SEARCH_VALUE_FOUND = 'LINEAR_SEARCH_VALUE_FOUND';
export const LINEAR_SEARCH_RESET = 'LINEAR_SEARCH_RESET';

// Binary Search Algorithm - Action Types
export const BINARY_SEARCH_CURRENT_VALUE = 'BINARY_SEARCH_CURRENT_VALUE';
export const BINARY_SEARCH_VALUE_FOUND = 'BINARY_SEARCH_VALUE_FOUND';
export const BINARY_SEARCH_RESET = 'BINARY_SEARCH_RESET';