export const GENERATE_GRID = 'GENERATE_GRID';
export const CHANGE_GRID_SIZE = 'CHANGE_GRID_SIZE';
export const SEARCH_ELEMENT = 'SEARCH_ELEMENT';

export const LINEAR_SEARCH_CURRENT_VALUE = 'LINEAR_SEARCH_CURRENT_VALUE';
export const LINEAR_SEARCH_VALUE_FOUND = 'LINEAR_SEARCH_VALUE_FOUND';